apiVersion: v1
kind: Namespace
metadata:
  name: policies
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: global
  namespace: policies
spec:
  clusterSet: global
---
