{
 "title": "ACM Right Sizing Virtualization Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(acm_rs_vm:cluster:cpu_request,cluster)"
    }
   },
   {
    "name": "profile",
    "label": "Profile",
    "query": {
     "query": "label_values(acm_rs_vm:namespace:cpu_usage{cluster=\"$cluster\"},profile)"
    }
   },
   { "name": "days", "label": "Aggregation", "query": "1d, 2d, 5d, 10d, 30d, 60d, 90d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(acm_rs_vm:namespace:cpu_request,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Recommendation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(acm_rs_vm:cluster:cpu_recommendation{cluster=\"$cluster\", profile=\"$profile\"}[$days:])"
    }
   ]
  },
  {
   "title": "CPU Utilization % - Top Underutilized VM Name (Namespace)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 19, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(20,\nacm_rs_vm:namespace:cpu_usage{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"}\n/\nacm_rs_vm:namespace:cpu_request{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"} < 1\n)",
     "legendFormat": "{{name}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(acm_rs_vm:cluster:cpu_usage{cluster=\"$cluster\", profile=\"$profile\"}[$days:])"
    }
   ]
  },
  {
   "title": "CPU Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(acm_rs_vm:cluster:cpu_request{cluster=\"$cluster\", profile=\"$profile\"}[$days:])"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(acm_rs_vm:cluster:cpu_usage{cluster=\"$cluster\", profile=\"$profile\"}[$days:]) / max_over_time(acm_rs_vm:cluster:cpu_request{cluster=\"$cluster\", profile=\"$profile\"}[$days:])"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "sort" } },
   "targets": [
    {
     "expr": "max_over_time(sum by (name) (acm_rs_vm:namespace:cpu_usage{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"})[$days:]) / max_over_time(sum by (name) (acm_rs_vm:namespace:cpu_request{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"})[$days:])"
    },
    {
     "expr": "max_over_time(sum by (name) (acm_rs_vm:namespace:cpu_usage{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"})[$days:])"
    },
    {
     "expr": "max_over_time(sum by (name) (acm_rs_vm:namespace:cpu_request{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"})[$days:])"
    },
    {
     "expr": "max_over_time(sum by (name) (acm_rs_vm:namespace:cpu_recommendation{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"})[$days:])"
    },
    {
     "expr": "label_join(\n  (\n    acm_rs_vm:namespace:cpu_usage{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"} + on(name, namespace) acm_rs_vm:namespace:cpu_request{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"}\n  ),\n  \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Memory Recommendation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(acm_rs_vm:cluster:memory_recommendation{cluster=\"$cluster\", profile=\"$profile\"}[$days:])"
    }
   ]
  },
  {
   "title": "Memory Utilization % - Top Underutilized VM Name (Namespace)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 19, "x": 4, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(20,\nacm_rs_vm:namespace:memory_usage{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"}\n/\nacm_rs_vm:namespace:memory_request{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"} < 1\n)",
     "legendFormat": "{{name}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(acm_rs_vm:cluster:memory_usage{cluster=\"$cluster\", profile=\"$profile\"}[$days:])"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(acm_rs_vm:cluster:memory_request{cluster=\"$cluster\", profile=\"$profile\"}[$days:])"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(acm_rs_vm:cluster:memory_usage{cluster=\"$cluster\", profile=\"$profile\"}[$days:]) / max_over_time(acm_rs_vm:cluster:memory_request{cluster=\"$cluster\", profile=\"$profile\"}[$days:])"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "max_over_time(sum by (name) (acm_rs_vm:namespace:memory_usage{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"})[$days:]) / max_over_time(sum by (name) (acm_rs_vm:namespace:memory_request{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"})[$days:])"
    },
    {
     "expr": "max_over_time(sum by (name) (acm_rs_vm:namespace:memory_usage{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"})[$days:])"
    },
    {
     "expr": "max_over_time(sum by (name) (acm_rs_vm:namespace:memory_request{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"})[$days:])"
    },
    {
     "expr": "max_over_time(sum by (name) (acm_rs_vm:namespace:memory_recommendation{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"})[$days:])"
    },
    {
     "expr": "label_join(\n  (\n    acm_rs_vm:namespace:memory_usage{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"} + on(name, namespace) acm_rs_vm:namespace:memory_request{cluster=\"$cluster\", profile=\"$profile\", namespace=~\"$namespace\"}\n  ),\n  \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    }
   ]
  }
 ]
}