apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: rs-policyset
  namespace: policies
spec:
  description: Right Sizing Policy Set
  policies:
    - rs-allowlist-policy
    - rs-prometheus-rules
    - vm-prometheus-rules
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: rs-policyset-binding
  namespace: policies
placementRef:
  name: rs-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: rs-policyset
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: rs-placement
  namespace: policies
spec:
  predicates: []
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
    - type: ManagedClusterConditionHubAccepted
      status: "True"
---

